[2023-10-25T04:58:24.923+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T04:53:20.228476+00:00/task_id=write_data_to_target_db permission to 509
[2023-10-25T04:58:24.924+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T04:53:20.228476+00:00/task_id=write_data_to_target_db permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T04:53:20.228476+00:00/task_id=write_data_to_target_db'
[2023-10-25T04:58:24.944+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T04:53:20.228476+00:00/task_id=write_data_to_target_db permission to 509
[2023-10-25T04:58:24.946+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T04:53:20.228476+00:00/task_id=write_data_to_target_db permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T04:53:20.228476+00:00/task_id=write_data_to_target_db'
[2023-10-25T04:58:24.968+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pionada_etl.write_data_to_target_db manual__2023-10-25T04:53:20.228476+00:00 [queued]>
[2023-10-25T04:58:24.976+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pionada_etl.write_data_to_target_db manual__2023-10-25T04:53:20.228476+00:00 [queued]>
[2023-10-25T04:58:24.977+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-25T04:58:24.991+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): write_data_to_target_db> on 2023-10-25 04:53:20.228476+00:00
[2023-10-25T04:58:24.996+0000] {standard_task_runner.py:57} INFO - Started process 650 to run task
[2023-10-25T04:58:24.998+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pionada_etl', 'write_data_to_target_db', 'manual__2023-10-25T04:53:20.228476+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/pionada_etl.py', '--cfg-path', '/tmp/tmp52s33mx2']
[2023-10-25T04:58:25.001+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask write_data_to_target_db
[2023-10-25T04:58:25.045+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T04:53:20.228476+00:00/task_id=write_data_to_target_db permission to 509
[2023-10-25T04:58:25.046+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T04:53:20.228476+00:00/task_id=write_data_to_target_db permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=pionada_etl/run_id=manual__2023-10-25T04:53:20.228476+00:00/task_id=write_data_to_target_db'
[2023-10-25T04:58:25.048+0000] {task_command.py:416} INFO - Running <TaskInstance: pionada_etl.write_data_to_target_db manual__2023-10-25T04:53:20.228476+00:00 [running]> on host d181ed02477e
[2023-10-25T04:58:25.290+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pionada_etl' AIRFLOW_CTX_TASK_ID='write_data_to_target_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T04:53:20.228476+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-25T04:53:20.228476+00:00'
[2023-10-25T04:58:25.385+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-25T04:58:25.392+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=pionada_etl, task_id=write_data_to_target_db, execution_date=20231025T045320, start_date=20231025T045824, end_date=20231025T045825
[2023-10-25T04:58:25.413+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-25T04:58:25.427+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
